services:
  postgres:
    image: postgres:16-alpine
    container_name: cofrin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cofrin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cofrin}
      POSTGRES_DB: ${POSTGRES_DB:-cofrin}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - cofrin_pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cofrin-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@cofrin.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-cofrin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - cofrin_pgadmin_data:/var/lib/pgadmin

volumes:
  cofrin_pg_data:
  cofrin_pgadmin_data:
